export const vowels = [
    {name: 'i', url: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Close_front_unrounded_vowel.ogg'},
    {name: 'u', url: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Close_back_rounded_vowel.ogg'},
    {name: 'ɪ', url: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Near-close_near-front_unrounded_vowel.ogg'},
    {name: 'ʊ', url: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Near-close_near-back_rounded_vowel.ogg'},
    {name: 'e', url: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Close-mid_front_unrounded_vowel.ogg'},
    {name: 'o', url: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Close-mid_back_rounded_vowel.ogg'},
    {name: 'ə', url: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Mid-central_vowel.ogg'},
    {name: 'ɛ', url: 'https://upload.wikimedia.org/wikipedia/commons/7/71/Open-mid_front_unrounded_vowel.ogg'},
    {name: 'ʌ', url: 'https://upload.wikimedia.org/wikipedia/commons/9/92/Open-mid_back_unrounded_vowel.ogg'},
    {name: 'ɔ', url: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Open-mid_back_rounded_vowel.ogg'},
    {name: 'æ', url: 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Near-open_front_unrounded_vowel.ogg'},
    {name: 'a', url: 'https://upload.wikimedia.org/wikipedia/commons/6/65/Open_front_unrounded_vowel.ogg'},
    {name: 'ɑ', url: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Open_back_unrounded_vowel.ogg'},
]
